import React from "react";

export const projects = [
  {
    id: 1,
    url: "",
    text: "project 1",
    thumbnail: "/images/avenue.jpg",
    sliderImages: [
      "/images/flowers.jpg",
      "/images/avenue.jpg",
      "/images/pink.jpg",
    ],
    desc: "This is about project 1",
    skills: ["HTML", "CSS", "JAVA"],
  },
  {
    id: 2,
    url: "lkajdljasd",
    text: "project 2",
    thumbnail: "/images/flowers.jpg",
    sliderImages: [
      "/images/flowers.jpg",
      "/images/avenue.jpg",
      "/images/pink.jpg",
      "/images/road.jpg",
      "/images/road1.jpg",
      "/images/tree.jpg",
    ],
    desc: "This is about project 2",
    skills: ["HTML", "CSS"],
  },
  {
    id: 3,
    url: "",
    text: "project 3",
    thumbnail: "/images/pink.jpg",
    sliderImages: [
      "/images/flowers.jpg",
      "/images/avenue.jpg",
      "/images/pink.jpg",
      "/images/road.jpg",
      "/images/road1.jpg",
      "/images/tree.jpg",
    ],
    desc: "This is about project 3",
    skills: ["CSS", "JAVA"],
  },
  {
    id: 4,
    url: "",
    text: "project 4",
    thumbnail: "/images/road.jpg",
    sliderImages: [
      "/images/flowers.jpg",
      "/images/avenue.jpg",
      "/images/tree.jpg",
    ],
    desc: "This is about project 4",
    skills: ["HTML", "JAVA"],
  },
  {
    id: 5,
    url: "",
    text: "project 5",
    thumbnail: "/images/road1.jpg",
    sliderImages: [
      "/images/flowers.jpg",
      "/images/avenue.jpg",
      "/images/pink.jpg",
      "/images/road.jpg",
    ],
    desc: "This is about project 5",
    skills: ["HTML", "CSS", "JAVA"],
  },
  {
    id: 6,
    url: "",
    text: "project 6",
    thumbnail: "/images/tree.jpg",
    sliderImages: [
      "/images/pink.jpg",
      "/images/road.jpg",
      "/images/road1.jpg",
      "/images/tree.jpg",
    ],
    desc: "This is about project 6",
    skills: ["HTML", "CSS", "JAVA"],
  },
  {
    id: 7,
    url: "",
    text: "project 7",
    thumbnail: "images/pink.jpg",
    sliderImages: [
      "/images/flowers.jpg",
      "/images/avenue.jpg",
      "/images/pink.jpg",
      "/images/road.jpg",
      "/images/road1.jpg",
      "/images/tree.jpg",
    ],
    desc: "This is about project 7",
    skills: ["HTML", "CSS", "JAVA"],
  },
];
export const links = [
  {
    id: 0,
    url: "/",
    text: "portfolio",
    // icon: <FaHome />,
  },
  {
    id: 1,
    url: "/about",
    text: "about",
    // icon: <FaUserFriends />,
  },
  {
    id: 2,
    url: "/contact",
    text: "contact",
    // icon: <FaFolderOpen />,
  },
  {
    id: 3,
    url: "/linkedin",
    text: "linkedin",
    // icon: <FaCalendarAlt />,
  },
];
